# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

matrix:
  include:
    - env: DB=mysql; MW=master; SMW=2.5.2
      php: 7
    - env: DB=mysql; MW=REL1_27;
      php: 5.6

install:
  - travis_retry composer self-update
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-compound-queries.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

cache:
  directories:
    - $HOME/.composer/cache
