# https://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

matrix:
  include:
    - env: DB=mysql; MW=master
      php: 7.1
    - env: DB=mysql; MW=REL1_29; TYPE=coverage
      php: 5.6
    - env: DB=sqlite; MW=REL1_27; SITELANG=ja
      php: 5.5
    - env: DB=mysql; MW=REL1_30
      php: 7

install:
  - travis_retry composer self-update
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-compound-queries.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

cache:
  directories:
    - $HOME/.composer/cache
