language: php

matrix:
  include:
    - env: DB=mysql; MW=master; SMW=~3.0@dev
      php: 7.2
    - env: DB=mysql; MW=REL1_27; SMW=~3.0@dev
      php: 5.6
    - env: DB=mysql; MW=REL1_28; SMW=~3.0@dev; TYPE=coverage
      php: 7.0
    - env: DB=sqlite; MW=REL1_29; SMW=~3.0@dev
      php: 7.1
    - env: DB=postgres; MW=REL1_30; SMW=~3.0@dev
      php: 7.1      
  allow_failures:
  # Broken due to https://phabricator.wikimedia.org/T188840
    - env: DB=mysql; MW=master; SMW=~3.0@dev

install:
  - travis_retry composer self-update
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-compound-queries.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

cache:
  directories:
    - $HOME/.composer/cache
