language: php

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=master; SMW=~4.0@dev
      php: 7.4
    - env: DB=sqlite; MW=REL1_33; SMW=~3.0@dev; TYPE=coverage
      php: 7.3
    - env: DB=postgres; MW=REL1_32; SMW=~3.0@dev; PHPUNIT=6.5.*
      php: 7.3
    - env: DB=mysql; MW=REL1_35; SMW=~4.0@dev; PHPUNIT=6.5.*
      php: 7.4
  allow_failures:
    - env: DB=mysql; MW=master; SMW=~4.0@dev

install:
  - travis_retry composer self-update
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-compound-queries.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

cache:
  directories:
    - $HOME/.composer/cache
