# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

matrix:
  include:
    - env: DBTYPE=mysql; MW=master; SMW=2.3.1
      php: 7
#    - env: DBTYPE=mysql; MW=1.23.0; SMW=2.3.1
#      php: 5.5
#    - env: DBTYPE=mysql; MW=1.24.0; SMW=2.3.1
#      php: 5.6
#    - env: DBTYPE=sqlite; MW=1.25.6; SMW=2.3.1
#      php: 5.6

install:
  - travis_retry composer self-update

before_script: bash ./tests/travis/before_script.sh

script: bash ./tests/travis/run-tests.sh

#after_success: bash ./build/travis/after_success.sh

cache:
  directories:
    - $HOME/.composer/cache
